export default {
  dsa: [
    // "InsertionSort",
    // "MergeSort",
    // "MaximumSubarray",
    // "MinHeap",
    // "HeapSort",
    // "QuickSort",

    // "Trie",
    // "DFSOnBST",
    // "LRU",
    // "LinearSearchList",
    // "BinarySearchList",
    // "TwoCrystalBalls",
    // "BubbleSort",
    // "SinglyLinkedList",
    // "DoublyLinkedList",
    // "Queue",
    // "Stack",
    // "ArrayList",
    // "MazeSolver",
    // "BTPreOrder",
    // "BTInOrder",
    // "BTPostOrder",
    // "BTBFS",
    // "CompareBinaryTrees",
    // "DFSOnBST",
    // "DFSGraphList",
    // "BFSGraphMatrix",
    // "Map",
  ] as const,
};
